export const CHANGE_REGION = 'CHANGE_REGION';
export const IS_CONNECTED = 'IS_CONNECTED';
export const SET_FEEDS = 'SET_FEEDS';
export const SET_LOADING = 'SET_LOADING';
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const UPDATE_GEOFENCE = 'UPDATE_GEOFENCE';
export const UPDATE_BATTERY = 'UPDATE_BATTERY';
